### ISSUE TITLE
Can't register a user account on your demo site

### ISSUE THREAD

**Issue by mihha** [Grashjs/frontend#12]
Can't register a user account on your trial site
https://grash-cmms.com/account/register

## Current behavior
When I click "Create your account" button, system reports the following
![image](https://user-images.githubusercontent.com/3791124/212262849-b482bfb8-6da5-4254-b67e-5d16d85b9f92.png)

## Expected behavior
I would expect that registration would work

## Steps to replicate behavior (include URLs)

1. fill in all the details
2. click "Create your account" button
3. successfully register for the account

If you didn't open the system for the registrations, then this is ok
If the system is opened for the registrations, maybe you could check the logs and see what could be the issue

Thank you in advance!

**Comment by iib0011** [comment]
It is a known issue with the db

**Comment by ambou-97** [comment]
It's resolved now !

You can continue testing our app.
