### ISSUE TITLE
Scroll to key features

### ISSUE THREAD

**Issue by iib0011** [Grashjs/frontend#14]
The web page doesn't scroll to the key features section when using this link [https://grash-cmms.com/#key-features](https://grash-cmms.com/#key-features)

## Current behavior
 If you click in the Key features button it scrolls to the section and changes the url from https://grash-cmms.com to https://grash-cmms.com/#key-features. But the web page doesn't scroll to the key features section when using this link [https://grash-cmms.com/#key-features](https://grash-cmms.com/#key-features).

## Expected behavior
It should scroll to the key Features sections

## Steps to replicate behavior (include URLs)

1. Go to this link [https://grash-cmms.com/#key-features](https://grash-cmms.com/#key-features)

**Comment by aminait** [comment]
Hi,

would love to contribute to this issue

**Comment by iib0011** [comment]
@aminait please look at [this](https://stackoverflow.com/questions/43441856/how-to-scroll-to-an-element). You need to surround the section with a div
